import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowDownLeft, ArrowUpRight, Bot, BookOpen, Check, ChevronDown, CircleHelp, Clock3, Command, Cpu, FileText, Headphones, LayoutDashboard, LifeBuoy, LoaderCircle, MessageSquareText, Plus, Search, Send, ShieldCheck, Sparkles, Ticket, WandSparkles, Wifi, X} from 'lucide-react';
import './style.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api';
const samples=['My VPN is not connecting. Authentication keeps failing.','My password has expired.','How do I troubleshoot Outlook synchronization?','I need Visual Studio Code installed on my laptop.','How do I configure a quantum flux capacitor?'];
async function call(path, options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok)throw Error(j.detail||'Something went wrong');return j}
function App(){
 const [page,setPage]=useState('portal'),[health,setHealth]=useState(null),[dash,setDash]=useState(null),[articles,setArticles]=useState([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[turns,setTurns]=useState([]),[toast,setToast]=useState(''),[search,setSearch]=useState('');
 const refresh=()=>Promise.all([call('/health').then(setHealth).catch(()=>setHealth({status:'offline'})),call('/dashboard').then(setDash).catch(()=>{}),call('/knowledge').then(setArticles).catch(()=>{})]);
 useEffect(()=>{refresh()},[]);useEffect(()=>{if(toast){let t=setTimeout(()=>setToast(''),3400);return()=>clearTimeout(t)}},[toast]);
 async function submit(text=input){if(!text.trim()||busy)return;setInput('');setBusy(true);setTurns(x=>[...x,{role:'user',text}]);try{const result=await call('/ask',{method:'POST',body:JSON.stringify({message:text})});setTurns(x=>[...x,{role:'assistant',text:result.answer,result}]);}catch(e){setTurns(x=>[...x,{role:'assistant',text:'I can’t reach the helpdesk service right now. Please check that the API is running.'}]);}finally{setBusy(false)}}
 async function doAction(result){try{let data;if(result.analysis.kind==='password'){data=await call('/automate',{method:'POST',body:JSON.stringify({message:turns.filter(x=>x.role==='user').at(-1)?.text||'Password reset'})});setToast(`Self-heal completed · ${data.ticket.number}`)}else if(result.analysis.kind==='software'){data=await call('/requests',{method:'POST',body:JSON.stringify({message:turns.filter(x=>x.role==='user').at(-1)?.text||'Request software'})});setToast(`Provisioning request created · ${data.request.number}`)}else{data=await call('/tickets',{method:'POST',body:JSON.stringify({message:turns.filter(x=>x.role==='user').at(-1)?.text||'Helpdesk request'})});setToast(`Ticket created · ${data.number}`)}await refresh()}catch(e){setToast(e.message)}}
 const nav=[['portal','Self-service',MessageSquareText],['dashboard','ITSM dashboard',LayoutDashboard],['knowledge','Knowledge base',BookOpen]];
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandmark"><Command size={19}/></div><div><b>helio</b><small>AI SERVICE DESK</small></div><ChevronDown className="brand-chevron" size={15}/></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(([id,name,Icon])=><button key={id} onClick={()=>setPage(id)} className={`navitem ${page===id?'active':''}`}><Icon size={18}/><span>{name}</span>{id==='dashboard'&&<span className="navdot"/>}</button>)}</nav><div className="side-bottom"><div className="help-card"><div className="help-icon"><Headphones size={17}/></div><div><b>Need a human?</b><span>Our team is here to help.</span></div><button onClick={()=>{setPage('portal');setInput('I need to speak with the IT helpdesk')}}><ArrowUpRight size={15}/></button></div><div className="profile"><div className="avatar">AM</div><div><b>Alex Morgan</b><span>Engineering · Employee</span></div><ChevronDown size={15}/></div></div></aside>
 <main className="main"><header><div className="crumb">Workspace <span>/</span> <b>{nav.find(n=>n[0]===page)?.[1]}</b></div><div className="headright"><span className={`statuspill ${health?.status==='ok'?'':'offline'}`}><i/>{health?.status==='ok'?'All systems operational':'Service unavailable'}</span><div className="avatar small">AM</div></div></header>
 {page==='portal'&&<section className="portal"><div className="welcome"><div className="eyebrow"><Sparkles size={14}/> YOUR AI-POWERED IT COMPANION</div><h1>Good morning, Alex<span className="period">.</span></h1><p>What can we help you with today?</p></div><div className="chat-panel"><div className="chat-top"><div className="bot-avatar"><Bot size={19}/><i/></div><div><b>Helio Assistant</b><span>Here to get you back to work</span></div><span className="secure"><ShieldCheck size={14}/> Secure session</span></div><div className="chat-body" id="chat-body">{turns.length===0?<div className="intro"><div className="intro-glyph"><WandSparkles size={25}/></div><h2>How can I make your day easier?</h2><p>Ask a question, report an issue, or request software. I’ll find the right path.</p><div className="suggestions">{samples.map(s=><button key={s} onClick={()=>submit(s)}><span>{s}</span><ArrowUpRight size={15}/></button>)}</div></div>:<div className="messages">{turns.map((t,i)=><div className={`message ${t.role}`} key={i}><div className="msg-icon">{t.role==='assistant'?<Bot size={16}/>:<span>AM</span>}</div><div className="bubble"><p>{t.text}</p>{t.result&&<Analysis result={t.result} action={()=>doAction(t.result)}/>}</div></div>)}{busy&&<div className="thinking"><LoaderCircle size={16}/> Searching approved knowledge…</div>}</div>}</div><form className="composer" onSubmit={e=>{e.preventDefault();submit()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Describe an issue or ask a question…"/><button className="send" disabled={!input.trim()||busy}><Send size={17}/></button><div className="composer-foot"><span><ShieldCheck size={12}/> Responses grounded in company knowledge</span><kbd>↵</kbd></div></form></div><div className="portal-foot"><span><ShieldCheck size={14}/> Your requests are private and secure</span><span>Powered by <b>Helio AI</b></span></div></section>}
 {page==='dashboard'&&<section className="page-content"><div className="page-title"><div><div className="eyebrow">OPERATIONS OVERVIEW</div><h1>ITSM dashboard<span className="period">.</span></h1><p>A live view of your service desk activity.</p></div><button className="outline-button" onClick={refresh}><Activity size={16}/> Refresh data</button></div><div className="metrics">{[['Total tickets',dash?.total||0,Ticket,'#eef1ff','#595bd4'],['Open tickets',dash?.open||0,Clock3,'#fff5e9','#dc943e'],['AI resolved',dash?.resolved||0,Sparkles,'#e9f8f0','#36a474'],['Escalated',dash?.escalated||0,ArrowUpRight,'#fff0ee','#de6b5a']].map(([label,value,Icon,bg,fg])=><div className="metric" key={label}><div className="metric-label">{label}<span className="metric-icon" style={{background:bg,color:fg}}><Icon size={17}/></span></div><strong>{value}</strong><small>{label==='Total tickets'?'All requests received':'Updated just now'}</small></div>)}</div><div className="dash-grid"><div className="card"><div className="card-head"><div><h3>Recent tickets</h3><span>Latest employee requests</span></div><span className="count">{dash?.tickets?.length||0}</span></div>{dash?.tickets?.length?dash.tickets.map(t=><div className="ticket-row" key={t.number}><div className="ticket-icon"><Ticket size={16}/></div><div className="ticket-info"><b>{t.summary}</b><span>{t.number} · {t.assignment_group}</span></div><span className={`badge ${t.state==='Resolved'?'green':t.state==='Escalated'?'red':'amber'}`}>{t.state}</span></div>):<Empty icon={Ticket} title="No tickets yet" text="Tickets will appear here when employees submit requests."/>}</div><div className="card"><div className="card-head"><div><h3>Automation activity</h3><span>Audited self-heal and provisioning actions</span></div><Activity size={17} className="muted"/></div>{dash?.recent_actions?.length?dash.recent_actions.map(a=><div className="activity-row" key={a.id}><div className={`activity-icon ${a.status==='Validated'?'success':''}`}><Check size={15}/></div><div><b>{a.action==='password_reset'?'Password reset':'Software provisioning'}</b><span>{a.target} · {a.ticket}</span></div><span className="badge green">{a.status}</span></div>):<Empty icon={Cpu} title="Ready when you are" text="Safe automated actions are recorded here."/>}</div></div><div className="card request-card"><div className="card-head"><div><h3>Software requests</h3><span>Mock provisioning queue</span></div><span className="count">{dash?.requests||0}</span></div>{dash?.requests_list?.length?dash.requests_list.map(r=><div className="ticket-row" key={r.number}><div className="ticket-icon violet"><Cpu size={16}/></div><div className="ticket-info"><b>{r.software}</b><span>{r.number}</span></div><span className="badge amber">{r.status}</span></div>):<Empty icon={Cpu} title="No provisioning requests" text="Try asking Helio to install Visual Studio Code."/>}</div></section>}
 {page==='knowledge'&&<section className="page-content"><div className="page-title"><div><div className="eyebrow">APPROVED SUPPORT CONTENT</div><h1>Knowledge base<span className="period">.</span></h1><p>Trusted guidance Helio uses to answer employee questions.</p></div><span className="article-total"><BookOpen size={16}/>{articles.length} articles</span></div><div className="searchbox"><Search size={17}/><input placeholder="Search support articles…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>⌘ K</kbd></div><div className="kb-grid">{articles.filter(a=>(a.title+' '+a.text+' '+a.category).toLowerCase().includes(search.toLowerCase())).map(a=><div className="kb-card" key={a.id}><div className="kb-card-top"><span className="kb-icon"><FileText size={17}/></span><span className="kb-id">{a.id}</span></div><span className="kb-category">{a.category}</span><h3>{a.title}</h3><p>{a.text}</p><div className="kb-bottom"><span><ShieldCheck size={13}/> Approved content</span><button onClick={()=>{setPage('portal');setInput(`Tell me about ${a.title}`)}}>Ask Helio <ArrowUpRight size={14}/></button></div></div>)}</div></section>}
 <footer className="app-footer"><span>Helio Service Desk <span>·</span> AI-assisted, human-supported</span><span>{health?.vector_db||'Knowledge retrieval'} <i/> {health?.database||'Local demo'}</span></footer></main>{toast&&<div className="toast"><Check size={17}/>{toast}<button onClick={()=>setToast('')}><X size={15}/></button></div>}</div>
}
function Analysis({result,action}){let a=result.analysis;return <div className="analysis"><div className="analysis-head"><span><Sparkles size={14}/> AI analysis</span><b>{Math.round(a.confidence*100)}% confidence</b></div><div className="analysis-tags"><span>{a.intent}</span><span>{a.category} / {a.subcategory}</span><span>{a.priority}</span></div>{result.sources?.length>0&&<div className="sources"><b><BookOpen size={13}/> Knowledge sources</b>{result.sources.map(s=><span key={s.id}>{s.title}<i>{Math.round(s.score*100)}%</i></span>)}</div>}{result.needs_escalation&&<div className="escalation"><CircleHelp size={14}/> Low confidence or no approved answer. Escalate for human review.</div>}<button className="action-btn" onClick={action}>{a.kind==='password'?<><WandSparkles size={15}/> Run safe self-heal</>:a.kind==='software'?<><Cpu size={15}/> Create provisioning request</>:<><Plus size={15}/> Create helpdesk ticket</>}</button></div>}
function Empty({icon:Icon,title,text}){return <div className="empty"><span><Icon size={20}/></span><b>{title}</b><p>{text}</p></div>}

createRoot(document.getElementById('root')).render(<App/>);
